name: "Setup build environment"
description: "Installs PHP, composer and composer dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup PHP with DOM extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: wp-cli
        extensions: dom

    - name: Set cache directories
      shell: bash
      run: composer config -g cache-dir "${{ github.workspace }}/.composer-cache"

    - name: Prepare composer cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.composer-cache
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install dependencies
      run: composer install
      shell: bash
