<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

$action = 'options.php';

?>

<div class="wrap">
	<h2>Scribit.pro Options</h2>
	<p>
		You can find your scribit.pro ID on our <a href="https://dashboard.scribit.pro" rel="nofollow" target="_blank">dashboard</a>,
		after you've created an account.
	</p>

	<form action="<?php echo esc_url( $action ); ?>" method="post">
		<?php settings_fields( \Scribit\WordPress\Hooks\AdminInit::OPTIONS_GROUP_NAME ); ?>
		<table class="form-table" role="presentation">
			<tbody>
			<tr>
				<?php $id = new \Scribit\WordPress\Settings\ScribitID(); ?>
				<th scope="row">
					<label for="<?php echo $id->key(); ?>"><?php _e( 'Your Scribit.Pro ID' ); ?></label>
				</th>
				<td>
					<input name="<?php echo $id->key(); ?>" type="text" id="<?php echo $id->key(); ?>"
					       value="<?php echo esc_attr( $id->value() ) ?>" class="regular-text ltr"
					>
				</td>
			</tr>
			</tbody>
		</table>

		<h2 class="title">Advanced settings</h2>
		<p>
			The default settings are usually good enough for 99% of the websites.
			We've made them configurable just in case your site is special :)
		</p>


		<table class="form-table" role="presentation">
			<tbody>
			<tr>
				<?php
				$wrapper       = new \Scribit\WordPress\Settings\WidgetWrapper();
				$selectedValue = $wrapper->value();
				?>
				<th scope="row">
					<label for="<?php echo $wrapper->key(); ?>"><?php _e( 'Widget toolbar placement' ); ?></label>
				</th>
				<td>
					<select name="<?php echo $wrapper->key() ?>">
						<?php foreach ( $wrapper->options() as $option ) { ?>
							<option
								value="<?php echo $option ?>" <?php echo $option === $selectedValue ? "selected" : null ?>>
								<?php _e( "wrapper_placment_" . $option ); ?>
							</option>
						<?php } ?>
					</select>
				</td>
			</tr>
			</tbody>
		</table>
		<p class='submit'>
			<input name='submit' type='submit' id='submit' class='button-primary'
			       value='<?php _e( "Save Changes" ) ?>'/>
		</p>
	</form>
</div>
