<?php

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

$action = 'options.php';

?>

<div class="wrap">
    <h2>Scribit.pro Options</h2>

    <form action="<?php echo esc_url($action); ?>" method="post">
        <?php settings_fields(\Scribit\WordPress\Hooks\AdminInit::OPTIONS_GROUP_NAME); ?>
        <h2 class="title">General settings</h2>
        <p>Todo: here's a short summary of what you are trying to configure.</p>


        <table class="form-table" role="presentation">
            <tbody>
            <tr>
                <?php $id = new \Scribit\WordPress\Settings\ScribitID(); ?>
                <th scope="row">
                    <label for="<?php echo $id->key; ?>"><?php echo $id->label(); ?></label>
                </th>
                <td>
                    <input name="<?php echo $id->key; ?>" type="text" id="<?php echo $id->key; ?>"
                           value="<?php echo esc_attr($id->value()) ?>" class="regular-text ltr"
                    >
                </td>
            </tr>
            </tbody>
        </table>
        <p class='submit'>
            <input name='submit' type='submit' id='submit' class='button-primary' value='<?php _e("Save Changes") ?>'/>
        </p>
    </form>
</div>
